# -*- coding: utf-8 -*-
"""fundnavgrowth.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wTDyzXD5cMUzyfHYWM2ajhm5lwR6_joW

USE DATASET FROM https://data.go.th/dataset/mf_nav_202004_th-csv
"""

!apt-get update                                                                          # อัพเดท Package ทั้งหมดใน VM ตัวนี้
!apt-get install openjdk-8-jdk-headless -qq > /dev/null                                  # ติดตั้ง Java Development Kit (จำเป็นสำหรับการติดตั้ง Spark)
!wget -q https://archive.apache.org/dist/spark/spark-3.1.2/spark-3.1.2-bin-hadoop2.7.tgz # ติดตั้ง Spark 3.1.2
!tar xzvf spark-3.1.2-bin-hadoop2.7.tgz                                                  # Unzip ไฟล์ Spark 3.1.2
!pip install -q findspark==1.3.0                                                         # ติดตั้ง Package Python สำหรับเชื่อมต่อกับ Spark

# Set enviroment variable ให้ Python รู้จัก Spark
import os
os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-8-openjdk-amd64"
os.environ["SPARK_HOME"] = "/content/spark-3.1.2-bin-hadoop2.7"

# ติดตั้ง PySpark ลงใน Python
!pip install pyspark==3.1.2

# สร้าง Spark Session เพิ้อใช้งาน Spark
from pyspark.sql import SparkSession
spark = SparkSession.builder.master("local[*]").getOrCreate()

dt_Jan22 = spark.read.csv('/content/sample_data/mf_nav_202201_th.csv', header = True, inferSchema = True, )

dt_May22 = spark.read.csv('/content/sample_data/mf_nav_202205_th.csv', header = True, inferSchema = True, )

dt_Jan22.printSchema()

dt_Jan22.summary().show()

dt_Jan22.summary("count").show()

from pyspark.sql.types import DoubleType
from pyspark.sql.functions import col

dt_Jan22 = dt_Jan22.withColumn("nav",dt_Jan22.nav.cast('double'))

dt_Jan22.printSchema()

# แปลงข้อมูลจาก Spark DataFrame ให้เป็น TempView ก่อน
dt_Jan22.createOrReplaceTempView("DataJan22")
dt_Jan22_sql = spark.sql("SELECT PROJ_ABBR_NAME,fund_compare, nav FROM DataJan22")
dt_Jan22_sql.show()

dt_Jan22_sql_result = spark.sql("""
SELECT PROJ_ABBR_NAME AS fund,fund_compare,
  CASE WHEN nav IS NULL THEN 0 ELSE nav END AS nav_Jan22
FROM DataJan22
""")
dt_Jan22_sql_result.show()

dt_Jan22_sql_result.printSchema()

dt_nav_Jan22 = dt_Jan22_sql_result.na.drop()
dt_nav_Jan22.show()
dt_nav_Jan22.summary("count").show()

dt_May22.summary().show()

dt_May22 = dt_May22.withColumn("nav",dt_May22.nav.cast('double'))

dt_Jan22.printSchema()
dt_May22.printSchema()

# แปลงข้อมูลจาก Spark DataFrame ให้เป็น TempView ก่อน
dt_May22.createOrReplaceTempView("DataMay22")
dt_May22_sql = spark.sql("SELECT PROJ_ABBR_NAME,fund_compare, nav FROM DataMay22")
dt_May22_sql.show()

dt_May22_sql.printSchema()

dt_May22_sql_result = spark.sql("""
SELECT PROJ_ABBR_NAME AS fund,fund_compare,
  CASE WHEN nav IS NULL THEN 0 ELSE nav END AS nav_May22
FROM DataMay22
""")
dt_May22_sql_result.show()

dt_May22_sql_result.printSchema()

dt_nav_May22 = dt_May22_sql_result.na.drop()
dt_nav_May22.show()
dt_nav_May22.summary("count").show()
dt_nav_May22.printSchema()

print((dt_nav_Jan22.count(), len(dt_nav_Jan22.columns)))

print((dt_nav_May22.count(), len(dt_nav_May22.columns)))

dt_nav_Jan22.createOrReplaceTempView("Jan22")
dt_nav_May22.createOrReplaceTempView("May22")
dt_nav_Jan22.summary("count").show()
dt_nav_May22.summary("count").show()
dt_nav_sql_result = spark.sql("""SELECT fund, May22.fund_compare AS fund_category, nav_Jan22, nav_May22 FROM Jan22 FULL JOIN May22 USING(fund) WHERE nav_Jan22 > 0 AND nav_May22 > 0 ORDER BY fund""")
dt_nav_sql_result.show()

print((dt_nav_sql_result.count(), len(dt_nav_sql_result.columns)))

dt_nav_sql_result.printSchema()

dt_nav_sql_result.summary("count").show()

dt_nav_sql_result.coalesce(1).write.csv('Fund_Data_2022.csv', header = True)

import pandas as pd

dt_pd = dt_nav_sql_result.toPandas()

dt_pd

dt_pd.to_csv("fundnavdata.csv", index=False)